# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pricing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpricing.proto\"@\n\x08PriceReq\x12\x0e\n\x06lot_id\x18\x01 \x01(\x05\x12\x12\n\nstart_time\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\t\";\n\x08PriceRsp\x12\r\n\x05total\x18\x01 \x01(\x01\x12\x11\n\trate_type\x18\x02 \x01(\t\x12\r\n\x05hours\x18\x03 \x01(\x05\x32\x38\n\x0ePricingService\x12&\n\x0e\x43\x61lculatePrice\x12\t.PriceReq\x1a\t.PriceRspb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pricing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICEREQ']._serialized_start=17
  _globals['_PRICEREQ']._serialized_end=81
  _globals['_PRICERSP']._serialized_start=83
  _globals['_PRICERSP']._serialized_end=142
  _globals['_PRICINGSERVICE']._serialized_start=144
  _globals['_PRICINGSERVICE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
